# gen_constants.cmake  -  invoked as a standalone script via cmake -P

function(random_uint32 out_var)
    string(RANDOM LENGTH 5 ALPHABET "0123456789" part_hi)
    string(RANDOM LENGTH 5 ALPHABET "0123456789" part_lo)

    # Strip leading zeros: math(EXPR) would misinterpret them as octal
    math(EXPR value "(${part_hi} * 100000 + ${part_lo}) % 4294967295" OUTPUT_FORMAT DECIMAL)
    set(${out_var} "${value}" PARENT_SCOPE)
endfunction()

# Generate the two LCG constants; enforce odd values for maximum LCG period
# (Hull-Dobell theorem requires multiplier A and increment C both odd
# when the modulus M = 2^32).
random_uint32(lcg_a)
random_uint32(lcg_c)

math(EXPR lcg_a "${lcg_a} | 1")   # set LSB -> guaranteed odd
math(EXPR lcg_c "${lcg_c} | 1")   # set LSB -> guaranteed odd

if(lcg_a EQUAL 0)
    set(lcg_a 1)
endif()

set(header_content
"//
// AUTO-GENERATED -- do not edit
// Generated by CMake at build time.
//
#ifndef SUSSHI_MEMCRYPT_CONSTANTS_H
#define SUSSHI_MEMCRYPT_CONSTANTS_H

#define LCG_MULTIPLIER  ${lcg_a}u
#define LCG_INCREMENT   ${lcg_c}u

#endif // SUSSHI_MEMCRYPT_CONSTANTS_H
")

# GEN_HEADER is passed in via -D from the add_custom_command below
file(WRITE "${GEN_HEADER}" "${header_content}")

message(STATUS "Generated: ${GEN_HEADER}")
