set(APPLICATION_VERSION_MAJOR "26")
set(APPLICATION_VERSION_MINOR "08")
set(APPLICATION_VERSION_PATCH "0")

set(APPLICATION_VERSION "${APPLICATION_VERSION_MAJOR}.${APPLICATION_VERSION_MINOR}.${APPLICATION_VERSION_PATCH}")
